### ISSUE TITLE
CometBFT integration setup

### ISSUE THREAD

**Issue by mconcat** [mconcat/helium#16]
## Overview

This issue covers the complete integration between Helium and CometBFT, including configuration, connection handling, and development environment setup.

## Context

Helium implements the ABCI++ protocol to communicate with CometBFT (formerly Tendermint) for consensus. While we have the ABCI server implementation, we need proper integration setup to run a complete blockchain node. This includes handling the network layer, peer discovery, and block production that CometBFT provides.

### Docker Compose Setup

Create a `docker-compose.yml` that runs both CometBFT and Helium together:

```yaml
version: '3.8'
services:
  cometbft:
    image: cometbft/cometbft:v0.38.0
    # Configuration for CometBFT
    
  helium:
    build: .
    depends_on:
      - cometbft
    # Configuration for Helium ABCI app
```

### CometBFT Configuration

1. **Configuration Template**
   Create template files for:
   - `config.toml` - CometBFT node configuration
   - `genesis.json` - Initial chain state
   - `priv_validator_key.json` - Validator key (for development)

2. **Key Configuration Parameters**
   ```toml
   [rpc]
   laddr = "tcp://0.0.0.0:26657"
   
   [p2p]
   laddr = "tcp://0.0.0.0:26656"
   persistent_peers = ""
   
   [consensus]
   timeout_commit = "5s"
   
   [mempool]
   size = 5000
   
   # ABCI connection
   proxy_app = "tcp://helium:26658"
   ```

### Connection Handling

Implement robust connection handling between Helium and CometBFT:

1. **Reconnection Logic**
   - Handle CometBFT restarts gracefully
   - Implement exponential backoff for reconnection attempts
   - Clear logging of connection status

2. **Health Checks**
   - Implement health endpoints for both services
   - Add liveness/readiness probes
   - Monitor ABCI connection status

3. **Error Handling**
   - Graceful degradation on connection loss
   - Clear error messages for operators
   - Automatic recovery mechanisms

### Development Scripts

Create helper scripts for developers:

1. **`scripts/init-testnet.sh`**
   ```bash
   #\!/bin/bash
   # Initialize a single-node testnet
   # - Generate validator key
   # - Create genesis file
   # - Initialize CometBFT
   # - Setup Helium configuration
   ```

2. **`scripts/reset-testnet.sh`**
   ```bash
   #\!/bin/bash
   # Clean all testnet data
   # Useful for development iteration
   ```

3. **`scripts/start-testnet.sh`**
   ```bash
   #\!/bin/bash
   # Start both CometBFT and Helium
   # With proper logging setup
   ```

### Multi-Node Setup

Support for running multiple nodes locally:

1. Create configurations for 4-node testnet
2. Different ports for each node
3. Proper peer discovery setup
4. Script to start/stop all nodes

### Integration Points

Ensure proper integration at these points:

1. **InitChain**
   - Genesis processing
   - Initial validator set
   - Chain ID validation

2. **Block Processing**
   - FinalizeBlock handling
   - Commit synchronization
   - App hash agreement

3. **Query Handling**
   - ABCI query routing
   - Proof verification
   - Height handling

## Testing Requirements

1. **Connection Tests**
   - Test reconnection scenarios
   - Network partition simulation
   - CometBFT restart handling

2. **Integration Tests**
   - Full block production cycle
   - Transaction inclusion
   - State synchronization

3. **Performance Tests**
   - Block production rate
   - Transaction throughput
   - Latency measurements

## Documentation

Create documentation for:
- Quick start guide for developers
- Production deployment considerations
- Troubleshooting common issues
- Configuration reference

## Dependencies

- ABCI server implementation in Helium
- Docker and docker-compose
- CometBFT v0.38.x compatibility

## Acceptance Criteria

- [ ] Docker compose setup works out of the box
- [ ] Can run single-node testnet with one command
- [ ] Multi-node testnet setup available
- [ ] Robust connection handling implemented
- [ ] Health checks and monitoring in place
- [ ] Integration tests passing
- [ ] Developer documentation complete

Related to epic: #14
